# Generated by Django 5.1 on 2024-09-08 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_date_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 8, 5, 8, 2, 976133)),
        ),
    ]
